---

ansible_groups: {}

ansible_playbooks:
  - 'testing_deployment.yml'

vagrant_provider: 'virtualbox'
vagrant_synced_folder_type: 'virtualbox'

vagrant_servers:
  - name: 'pip-trusty'
    box: 'ubuntu/trusty64'
    family: 'debian'
  - name: 'pip-xenial'
    box: 'ubuntu/xenial64'
    family: 'debian'

# Example of a vagrant server description.
# Only name, box and family are mandatory:
#  - name: 'pip-trusty'
#    box: 'ubuntu/trusty64'
#    family: 'debian'
#    cpus: 1
#    memory: 512
#    forwarded_port: []
